model_name: lcps
dataset:
    name: nuscenes
    version: v1.0-trainval
    path: ../data/nuscenes
    sample_pkl_path: ../data/nuscenes/pkl_files
    rotate_aug: True
    flip_aug: True
    max_volume_space: [ 100, 3.1415926, 3 ]
    min_volume_space: [ 0, -3.1415926, -5 ]
    gt_generator:
        sigma: 5
    grid_size: [480,360,32]
    num_worker: 4
    min_points: 15
model:
    pix_fusion: True
    pix_fusion_path: ../checkpoints/resnet18-5c106cde.pth
    use_sara: True
    use_att: True
    model_load_path: ./nusc_79.8.pt
    val_batch_size: 2
    post_proc:
        threshold: 0.1
        nms_kernel: 5
        top_k: 100